docs/ABOUT.md

This PR is meant to prepare the track for Nexercism launch as per https://github.com/exercism/meta/issues/85
I've added line breaks for each sentences and replaced CF to CFML for consistency.
@bdw429s, please let me know if I should changing something

Changes ABOUT.md for Nexercism per /exercism/meta #85

---

config.json
config/maintainers.json

I ran 'configlet fmt .' to normalize the configs before I start editing them.

Normalize the configs

---

config.json
config/maintainers.json

**Before merging this, please merge https://github.com/exercism/cfml/pull/61** - that will minimize the diff in this PR.

[WIP] Rename the track from ColdFusion to CFML

---

config.json
exercises/anagram/Anagram.cfc
exercises/anagram/AnagramTest.cfc
exercises/anagram/README.md
exercises/anagram/Solution.cfc
exercises/anagram/SolutionTest.cfc
exercises/anagram/TestRunner.cfc
exercises/anagram/box.json
exercises/anagram/index.cfm

added anagram exercise

---

.gitattributes
config.json
tasks/FormatConfig.cfc
tasks/GenerateReadme.cfc
tasks/ScaffoldExercise.cfc

@bdw429s Here is my attempt at the README task runner. Hope this looks ok.

added task runner to generate README.md files

---

tasks/GenerateReadme.cfc

@bdw429s This should fix the encoding issue in the pangram exercise

specified utf-8 encoding to fix encoding issue

---

exercises/bob/README.md
exercises/gigasecond/README.md
exercises/hamming/README.md
exercises/saddle-points/README.md

Regenerated out of date READMEs using `configlet`

Update READMEs using configlet

---

exercises/practice/acronym/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/flatten-array/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/isogram/.meta/config.json
exercises/practice/largest-series-product/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/markdown/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/saddle-points/.meta/config.json
exercises/practice/scrabble-score/.meta/config.json
exercises/practice/secret-handshake/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/triangle/.meta/config.json
exercises/practice/word-count/.meta/config.json

To help tracks define the files in the exercise's `.meta/config.json` file, we've added support for defining these file patterns in the track's `config.json` file. See [this PR](https://github.com/exercism/docs/pull/58).
This PR updates the file paths defined in the `files` property of each exercise's `.meta/config.json` file according to the file patterns defined in the track's `config.json` file.
We only update a file path in the `.meta/config.json` file if:
- The file path pattern is a non-empty array in the `config.json` file
- The file path pattern is either not set or an empty array in the `.meta/config.json` file
This means that exercises that had already defined files in the `.meta/config.json` won't be touched in this PR.
Note that this PR is just an easy way for tracks to …

🤖 Sync exercise files keys based on file path patterns

---

README.md

fix typo: PascalCased for components not camelCase

PascalCased for components

---

exercises/practice/acronym/.docs/instructions.md
exercises/practice/anagram/.docs/instructions.md
exercises/practice/atbash-cipher/.docs/instructions.md
exercises/practice/bob/.docs/instructions.md
exercises/practice/diamond/.docs/instructions.md
exercises/practice/difference-of-squares/.docs/instructions.md
exercises/practice/flatten-array/.docs/instructions.md
exercises/practice/gigasecond/.docs/instructions.md
exercises/practice/grains/.docs/instructions.md
exercises/practice/hamming/.docs/instructions.md
exercises/practice/hello-world/.docs/instructions.md
exercises/practice/isogram/.docs/instructions.md
exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/leap/.docs/instructions.md
exercises/practice/luhn/.docs/instructions.md
exercises/practice/markdown/.docs/instructions.md
exercises/practice/nth-prime/.docs/instructions.md
exercises/practice/pangram/.docs/instructions.md
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/raindrops/.docs/instructions.md
exercises/practice/rna-transcription/.docs/instructions.md
exercises/practice/saddle-points/.docs/instructions.md
exercises/practice/secret-handshake/.docs/instructions.md
exercises/practice/space-age/.docs/instructions.md
exercises/practice/sum-of-multiples/.docs/instructions.md
exercises/practice/triangle/.docs/instructions.md
exercises/practice/word-count/.docs/instructions.md

This brings in recent improvements to the docs for all practice exercises.

Sync docs with problem-specifications

---

exercises/practice/acronym/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/flatten-array/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/largest-series-product/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/markdown/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/saddle-points/.meta/config.json
exercises/practice/secret-handshake/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/triangle/.meta/config.json

This brings in recent improvements to the metadata for all practice exercises.

Sync metadata with problem-specifications

---

exercises/practice/acronym/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/flatten-array/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/isogram/.meta/config.json
exercises/practice/largest-series-product/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/markdown/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/saddle-points/.meta/config.json
exercises/practice/scrabble-score/.meta/config.json
exercises/practice/secret-handshake/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/triangle/.meta/config.json
exercises/practice/word-count/.meta/config.json

This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.

Reformat exercise config files

---

exercises/practice/acronym/.docs/instructions.append.md
exercises/practice/anagram/.docs/instructions.append.md
exercises/practice/atbash-cipher/.docs/instructions.append.md
exercises/practice/bob/.docs/instructions.append.md
exercises/practice/diamond/.docs/instructions.append.md
exercises/practice/difference-of-squares/.docs/instructions.append.md
exercises/practice/flatten-array/.docs/instructions.append.md
exercises/practice/gigasecond/.docs/instructions.append.md
exercises/practice/grains/.docs/instructions.append.md
exercises/practice/hamming/.docs/instructions.append.md
exercises/practice/isogram/.docs/instructions.append.md
exercises/practice/largest-series-product/.docs/instructions.append.md
exercises/practice/luhn/.docs/instructions.append.md
exercises/practice/markdown/.docs/instructions.append.md
exercises/practice/nth-prime/.docs/instructions.append.md
exercises/practice/pangram/.docs/instructions.append.md
exercises/practice/pig-latin/.docs/instructions.append.md
exercises/practice/raindrops/.docs/instructions.append.md
exercises/practice/rna-transcription/.docs/instructions.append.md
exercises/practice/saddle-points/.docs/instructions.append.md
exercises/practice/scrabble-score/.docs/instructions.append.md
exercises/practice/secret-handshake/.docs/instructions.append.md
exercises/practice/space-age/.docs/instructions.append.md
exercises/practice/sum-of-multiples/.docs/instructions.append.md
exercises/practice/triangle/.docs/instructions.append.md
exercises/practice/word-count/.docs/instructions.append.md

The presence of an append file means that syncing with
problem-specifications requires a manual, visual verification
that the changes to the instructions don't contradict what
is written in the append file.
This removes the unused append files, allowing automatic
updates to exercise descriptions.

Remove unused append files

---

config.json

Pulled from [Exercism About Page](https://exercism.org/tracks/cfml).  Might need massaging.
1. **JIT compilation**: _Compiles to byte code and is dynamically evaluated on the Java Virtual Machine._
2. **Multi-paradigm**: _Supports classical Object Oriented as well as functional programming._
3. **Robust templating language**: _Easy, HTML-like syntax ideal for building a wide variety of web applications._
4. **Leverage the power of Java**: _Needing something extra? Drop in any jars you need and instantiate Java objects directly in your code._
5. **Built for the web**:  _Natively convert from HTML to PDF, parse XML, spin up APIs, access databases, or write to S3._  
6. **Batteries included**: _Be productive without installing many packages. Just about anything you need comes packaged._

[Track]: Added Key Language Features & Icons.

---

config.json
exercises/practice/run-length-encoding/.docs/instructions.md
exercises/practice/run-length-encoding/.meta/Example.cfc
exercises/practice/run-length-encoding/.meta/ExampleTest.cfc
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/run-length-encoding/.meta/tests.toml
exercises/practice/run-length-encoding/RunLengthEncoding.cfc
exercises/practice/run-length-encoding/RunLengthEncodingTest.cfc
exercises/practice/run-length-encoding/TestRunner.cfc
exercises/practice/run-length-encoding/box.json
exercises/practice/run-length-encoding/index.cfm

Required for December Diversions (probably)

new run-length-encoding exercise

---

config.json
exercises/practice/darts/.docs/instructions.md
exercises/practice/darts/.meta/Example.cfc
exercises/practice/darts/.meta/ExampleTest.cfc
exercises/practice/darts/.meta/config.json
exercises/practice/darts/.meta/tests.toml
exercises/practice/darts/Darts.cfc
exercises/practice/darts/DartsTest.cfc
exercises/practice/darts/TestRunner.cfc
exercises/practice/darts/box.json
exercises/practice/darts/index.cfm

The test generator failed to unwrap the test cases so I had to add them by hand.

Add darts exercise

---

config.json
exercises/practice/dnd-character/.docs/instructions.md
exercises/practice/dnd-character/.meta/Example.cfc
exercises/practice/dnd-character/.meta/ExampleTest.cfc
exercises/practice/dnd-character/.meta/config.json
exercises/practice/dnd-character/.meta/tests.toml
exercises/practice/dnd-character/DndCharacter.cfc
exercises/practice/dnd-character/DndCharacterTest.cfc
exercises/practice/dnd-character/TestRunner.cfc
exercises/practice/dnd-character/box.json
exercises/practice/dnd-character/index.cfm

One of the December Diversions exercises

new dnd-character exercise

---

README.md

@ErikSchierboom, I missed this tweak earlier.

Add CI test badge to README

---

config.json
exercises/practice/reverse-string/.docs/instructions.md
exercises/practice/reverse-string/.meta/Example.cfc
exercises/practice/reverse-string/.meta/ExampleTest.cfc
exercises/practice/reverse-string/.meta/config.json
exercises/practice/reverse-string/.meta/tests.toml
exercises/practice/reverse-string/ReverseString.cfc
exercises/practice/reverse-string/ReverseStringTest.cfc
exercises/practice/reverse-string/TestRunner.cfc
exercises/practice/reverse-string/box.json
exercises/practice/reverse-string/index.cfm

Add reverse-string

---

config.json
exercises/practice/strain/.docs/instructions.md
exercises/practice/strain/.meta/Example.cfc
exercises/practice/strain/.meta/ExampleTest.cfc
exercises/practice/strain/.meta/config.json
exercises/practice/strain/.meta/tests.toml
exercises/practice/strain/Strain.cfc
exercises/practice/strain/StrainTest.cfc
exercises/practice/strain/TestRunner.cfc
exercises/practice/strain/box.json
exercises/practice/strain/index.cfm

Add strain

---

config.json
exercises/practice/perfect-numbers/.docs/instructions.md
exercises/practice/perfect-numbers/.meta/Example.cfc
exercises/practice/perfect-numbers/.meta/ExampleTest.cfc
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/perfect-numbers/.meta/tests.toml
exercises/practice/perfect-numbers/PerfectNumbers.cfc
exercises/practice/perfect-numbers/PerfectNumbersTest.cfc
exercises/practice/perfect-numbers/TestRunner.cfc
exercises/practice/perfect-numbers/box.json
exercises/practice/perfect-numbers/index.cfm

Add perfect-numbers

---

config.json
exercises/practice/etl/.docs/instructions.md
exercises/practice/etl/.docs/introduction.md
exercises/practice/etl/.meta/Example.cfc
exercises/practice/etl/.meta/ExampleTest.cfc
exercises/practice/etl/.meta/config.json
exercises/practice/etl/.meta/tests.toml
exercises/practice/etl/Etl.cfc
exercises/practice/etl/EtlTest.cfc
exercises/practice/etl/TestRunner.cfc
exercises/practice/etl/box.json
exercises/practice/etl/index.cfm

Add ETL exercise

---

config.json
exercises/practice/square-root/.docs/instructions.md
exercises/practice/square-root/.meta/Example.cfc
exercises/practice/square-root/.meta/ExampleTest.cfc
exercises/practice/square-root/.meta/config.json
exercises/practice/square-root/.meta/tests.toml
exercises/practice/square-root/SquareRoot.cfc
exercises/practice/square-root/SquareRootTest.cfc
exercises/practice/square-root/TestRunner.cfc
exercises/practice/square-root/box.json
exercises/practice/square-root/index.cfm

Add square-root

---

config.json
exercises/practice/roman-numerals/.docs/instructions.md
exercises/practice/roman-numerals/.meta/Example.cfc
exercises/practice/roman-numerals/.meta/ExampleTest.cfc
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/RomanNumerals.cfc
exercises/practice/roman-numerals/RomanNumeralsTest.cfc
exercises/practice/roman-numerals/TestRunner.cfc
exercises/practice/roman-numerals/box.json
exercises/practice/roman-numerals/index.cfm

Add roman-numerals

---

config.json
exercises/practice/robot-simulator/.docs/instructions.md
exercises/practice/robot-simulator/.meta/Example.cfc
exercises/practice/robot-simulator/.meta/ExampleTest.cfc
exercises/practice/robot-simulator/.meta/config.json
exercises/practice/robot-simulator/.meta/tests.toml
exercises/practice/robot-simulator/RobotSimulator.cfc
exercises/practice/robot-simulator/RobotSimulatorTest.cfc
exercises/practice/robot-simulator/TestRunner.cfc
exercises/practice/robot-simulator/box.json
exercises/practice/robot-simulator/index.cfm

@ErikSchierboom, for your review.

Add robot-simulator exercise

---

config.json
exercises/practice/list-ops/.docs/instructions.md
exercises/practice/list-ops/.meta/Example.cfc
exercises/practice/list-ops/.meta/ExampleTest.cfc
exercises/practice/list-ops/.meta/config.json
exercises/practice/list-ops/.meta/tests.toml
exercises/practice/list-ops/ListOps.cfc
exercises/practice/list-ops/ListOpsTest.cfc
exercises/practice/list-ops/TestRunner.cfc
exercises/practice/list-ops/box.json
exercises/practice/list-ops/index.cfm

Add list-ops

---

config.json
exercises/practice/circular-buffer/.docs/instructions.md
exercises/practice/circular-buffer/.meta/Example.cfc
exercises/practice/circular-buffer/.meta/ExampleTest.cfc
exercises/practice/circular-buffer/.meta/config.json
exercises/practice/circular-buffer/.meta/tests.toml
exercises/practice/circular-buffer/CircularBuffer.cfc
exercises/practice/circular-buffer/CircularBufferTest.cfc
exercises/practice/circular-buffer/TestRunner.cfc
exercises/practice/circular-buffer/box.json
exercises/practice/circular-buffer/index.cfm

Add circular buffer
